### ISSUE TITLE
"templates" folder location

### ISSUE THREAD

**Issue by pgupta2050** [darwinlau/CASPR#10]
While loading a new robot, the GUI looks for the "templates" folder inside "/CASPR/data/" location. It is currently placed in the "/CASPR/data/model_config/" location.
![image](https://user-images.githubusercontent.com/76854988/107823513-e95c9400-6d4d-11eb-8d27-a15e019e0874.png)

**Comment by darwinlau** [comment]
Thank you for letting us know this bug, may I ask which model this error was thrown for? Or is this a new robot you created? If so, where did you try to create it? Thank you!

**Comment by pgupta2050** [comment]
This was seen for a new robot I created. I created it manually by placing the  .xml files in a folder with the same name as the robot. The folder itself is placed inside "data/model_config/models/"
I appended the model_list.csv manually. After copying the templates folder to the location: " /CASPR/data/", the GUI is able to load it too. I have run a few simulations with this new robot and everything else is great.

**Comment by darwinlau** [comment]
Ah.. thanks for the information. This is actually due to you manually creating the XML files and folder, so the location of the dtd file at the start of your XML points to the wrong folder structure as we use relative pathing. To resolve this manually, you can modify the line <!DOCTYPE bodies_system SYSTEM "../../../../templates/bodies.dtd"> in your XML files, note the number of ../

But actually, we suggest you to use the "CASPR_Model_Manager" (just type this in the command line) to create your robots, then it would have the right link to the dtd, rather than manually creating and copying files. The CASPR_Model_Manager would automatically create the XML files etc.
