### ISSUE TITLE
Usage of 'base_rotating_pulley' cable attachment

### ISSUE THREAD

**Issue by Costyco** [darwinlau/CASPR#4]
Dear Sirs,
I have lack of understanding how this parameter is used, and unfortunatelly there is no explanation on it in the documentation. The structure is as follows:
...
<attachments>
          <base_rotating_pulley>
          <fixed_location>1.659 -2.850 3.221</fixed_location>
          <pulley_radius>0.045</pulley_radius>
          <cable_entry_vector>0 0 1</cable_entry_vector>
          </base_rotating_pulley>
...
What does correspond to fixed_location and cable_entry_vector? Does CASPR have an implementation for caster-like rotating pulleys? (https://en.wikipedia.org/wiki/Caster)

**Comment by xxdinglaling** [comment]
Hi Costyco, thanks for your question, since CASPR is still under development, it is unfortunate that the available documentation is limited.

<Base_rotating_pulley> actually defining Caster like pulleys, but assuming the cable entry vector aligns with the axis of rotation, so a fixed location can be defined
<pulley_radius> defines the radius of the pulley
<fixed_location> is the point where won't change when the central kingpin rotates, also it is the tangent between incoming cable and pulley 
<cable_entry_vector> simply speaking is the axis of rotation of central kingpin, a normal vector specifying the direction of the cable gets into the pulley

![slide1](https://user-images.githubusercontent.com/20534371/39798787-790753b4-5394-11e8-8404-eae71936e5dd.JPG)

Here's another example
![slide2](https://user-images.githubusercontent.com/20534371/39798790-7c2715b6-5394-11e8-93fa-27760928bac0.JPG)

**Comment by Costyco** [comment]
Thank you very much for such a thorough explanation. Luckily, we have pulleys of the corresponding type.
Taking the above into account, how does CASPR calculate the length of a cable? An attachment point will be <fixed_location>, then cable goes over the pulley curvature and then the straight segment, am I right?

**Comment by xxdinglaling** [comment]
Yes, that's correct, you can also take a look on the tutorial, for defining cable attachment points! https://www.youtube.com/watch?v=N0zYohXRCAQ&list=PLZCfv3Lre4aVbsS8zFYlg2x-kPuB-rrRC&index=2

**Comment by Costyco** [comment]
Good job! Thank you!

**Comment by darwinlau** [comment]
Hi Costyco, thanks for the question and I hope we've answered it? If so we'll close the issue. Though, it would be great to know more about your institution, application using CASPR and research/development! Feel free to send me an e-mail at darwinlau@cuhk.edu.hk and maybe we can communicate more there?
